#!/bin/bash

. /usr/lib/live-swapfile/functions.sh

echo "getting list of partitions" >> ${LOGFILE}
for DEVICE in $(blkid -o device | grep -vE "/(loop|ram|dm-|fd)")
do
	echo "checking device ${DEVICE}" >> ${LOGFILE}
	get_mount_point "${DEVICE}"
		
	# search and activate writable, unused swap file on the device
	SWAPFILE="$(ls -1d ${MOUNTPOINT}/[Ll][Ii][Vv][Ee].[Ss][Ww][Pp] 2>/dev/null)"
	if [ -n "${SWAPFILE}" ]
	then
		echo " found swap file \"${SWAPFILE}\"" >> ${LOGFILE}
		if [ -w "${SWAPFILE}" ]
		then
			echo " ${SWAPFILE} is writable" >> ${LOGFILE}
			if grep -q ${SWAPFILE} /proc/swaps
			then
				echo " ${SWAPFILE} is already in use" >> ${LOGFILE}
			else
				echo " ${SWAPFILE} is not yet in use" >> ${LOGFILE}
				if swapon "${SWAPFILE}" >/dev/null 2>&1
				then
					echo " activated swap file ${SWAPFILE}" >> ${LOGFILE}
					UMOUNT=""
				else
					echo " ERROR: could not activate swap file ${SWAPFILE}" >> ${LOGFILE}
				fi
			fi
		else
			echo " ${SWAPFILE} is not writable" >> ${LOGFILE}
		fi
	else
		echo " found no swap file in ${MOUNTPOINT}" >> ${LOGFILE}
	fi
		
	# cleanup
	if [ -n "${UMOUNT}" ]
	then
		umount ${DEVICE}
	fi
done
